const API = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? 'http://localhost:8000' : 'http://backend:8000';
const app = document.getElementById('app');
const modalRoot = document.getElementById('modal-root');
const title = document.getElementById('page-title');
let uses = [];

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path, opts={}) { const r = await fetch(API + path, {headers:{'Content-Type':'application/json'}, ...opts}); if(!r.ok) throw new Error((await r.json()).detail || r.statusText); return r.json(); }

function badgeFor(outcome){
  if(/APPLICABLE|DEPLOYER/.test(outcome) && !/REVIEW/.test(outcome)) return 'good';
  if(/REVIEW|UNDETERMINED/.test(outcome)) return 'warn';
  return '';
}
function labelDimension(d){return ({REGULATORY_SCOPE:'EU AI Act scope',ACTOR_ROLE:'Your role',HIGH_RISK:'High-risk rules',TRANSPARENCY:'Transparency'})[d]||d.replaceAll('_',' ')}
function labelOutcome(o){return o.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}

async function loadUses(){ uses = await api('/api/ai-uses'); }
function navActive(view){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}

async function renderHome(){
  navActive('home'); title.textContent='Overview'; await loadUses();
  app.innerHTML=`<div class="grid">
    <div class="panel hero"><p class="eyebrow">GOVERNANCE AT A GLANCE</p><h2>${uses.length ? 'Your AI portfolio is taking shape.' : 'Start with the AI your teams actually use.'}</h2><p class="muted">The center translates simple business facts into rules, risks, safeguards and actions — without asking users to interpret the law themselves.</p>
      <div class="stat-grid"><div class="stat"><strong>${uses.length}</strong><span>AI uses</span></div><div class="stat"><strong>${uses.length}</strong><span>Open governance cases</span></div><div class="stat"><strong>${uses.length ? '1+' : '0'}</strong><span>Rules checks</span></div><div class="stat"><strong>${uses.length ? 'Active' : 'Ready'}</strong><span>Prototype status</span></div></div>
    </div>
    <div class="panel side-panel"><p class="eyebrow">HOW IT WORKS</p><h2>A guided journey for every AI use</h2><div class="journey">${['done','active','','','',''].map(x=>`<div class="journey-step ${x}"></div>`).join('')}</div><div class="journey-labels"><span>Your AI</span><span>Rules</span><span>Risks</span><span>Safeguards</span><span>Approve</span><span>Operate</span></div><p class="muted" style="margin-top:18px">Each AI use follows its own governance journey. Organisation-wide governance, roles and competence sit above the portfolio.</p></div>
    <div class="panel" style="grid-column:span 12"><div class="section-title"><h2>Recent AI uses</h2><button class="secondary" onclick="renderPortfolio()">View portfolio</button></div>${renderUseList(uses)}</div>
  </div>`;
}

function renderUseList(items){
  if(!items.length) return `<div class="empty"><div class="icon">◎</div><h2>No AI uses yet</h2><p class="muted">Add a use in business language. The governance model is created behind the scenes.</p><button class="primary" onclick="openWizard()">Add your first AI use</button></div>`;
  return `<div class="ai-list">${items.map(u=>`<div class="ai-card" onclick="openCard('${u.id}')"><div class="section-title"><div><p class="eyebrow">AI USE</p><h3>${esc(u.name)}</h3></div><span class="pill warn">${esc(u.status)}</span></div><p class="muted">${esc(u.purpose)}</p><div class="card-meta"><span class="pill good">Rules check available</span><span class="pill">Governance case</span></div></div>`).join('')}</div>`;
}

async function renderPortfolio(){navActive('portfolio'); title.textContent='My AI'; await loadUses(); app.innerHTML=`<div class="panel"><div class="section-title"><div><p class="eyebrow">AI PORTFOLIO</p><h2>AI uses</h2></div><button class="primary" onclick="openWizard()">+ Add AI use</button></div>${renderUseList(uses)}</div>`;}
async function renderActions(){navActive('actions'); title.textContent='My work'; await loadUses(); let cards=[]; for(const u of uses){try{cards.push(await api(`/api/ai-uses/${u.id}/card`))}catch{}} const actions=cards.flatMap(c=>(c.actions||[]).map(a=>({...a,ai:c.name}))); app.innerHTML=`<div class="panel"><div class="section-title"><div><p class="eyebrow">YOUR WORK</p><h2>Open actions</h2></div></div>${actions.length?`<div class="actions-list">${actions.map(a=>`<div class="action"><div class="priority ${a.priority}"></div><div><h4>${esc(a.title)}</h4><p>${esc(a.ai)} · ${esc(a.description)}</p></div><span class="pill ${a.priority==='HIGH'?'warn':''}">${esc(a.priority)}</span></div>`).join('')}</div>`:`<div class="empty"><h2>No generated actions yet</h2><p class="muted">Run a Rules Check on an AI use to generate governance work.</p></div>`}</div>`;}

async function openCard(id){
  const c=await api(`/api/ai-uses/${id}/card`); navActive('portfolio'); title.textContent=c.name;
  const hasRules=c.classifications.length>0;
  let phaseC=null, approval=null, monitoring=null;
  try{ phaseC=await api(`/api/governance-cases/${c.governance.case_id}/phase-c`) }catch{}
  try{ approval=await api(`/api/governance-cases/${c.governance.case_id}/approval`) }catch{}
  try{ monitoring=await api(`/api/governance-cases/${c.governance.case_id}/monitoring`) }catch{}
  const hasRisk=!!(phaseC&&phaseC.assessment_started);
  const readySafeguards=phaseC?phaseC.summary.safeguards_ready:0;
  const totalSafeguards=phaseC?phaseC.summary.safeguard_count:0;
  const approved=!!(approval&&approval.decision&&['APPROVED','APPROVED_WITH_CONDITIONS'].includes(approval.decision.outcome));
  const monitored=!!(monitoring&&monitoring.active);
  const journey=['done',hasRules?'done':'active',hasRisk?'done':(hasRules?'active':''),hasRisk?(readySafeguards===totalSafeguards&&totalSafeguards?'done':'active'):'',approved?'done':(hasRisk?'active':''),monitored?'active':''];
  let nextTitle='Run the Rules Check', nextCopy='We will use the facts you supplied to screen scope, actor role and key EU AI Act classification dimensions.', nextButton=`<button class="primary" onclick="runRules('${c.governance.case_id}','${id}')">Run Rules Check</button>`;
  if(hasRules&&!hasRisk){ nextTitle='Review risks & impacts'; nextCopy='The Rules Check identified governance work. Start a plain-language risk review and suggested safeguards.'; nextButton=`<button class="primary" onclick="startRiskReview('${c.governance.case_id}','${id}')">Start risk review</button><div style="height:9px"></div><button class="secondary" onclick="showRules('${id}')">View Rules Check</button>`; }
  if(hasRisk&&!approved){ nextTitle=approval?.readiness?.ready?'Ready for approval':'Prepare for approval'; nextCopy=approval?.readiness?.ready?'Risks, safeguards and proof meet the prototype approval gate. An accountable approver can now decide.':`${approval?.readiness?.blockers?.length||0} approval blockers remain.`; nextButton=`<button class="primary" onclick="showApproval('${c.governance.case_id}','${id}')">Open approval</button><div style="height:9px"></div><button class="secondary" onclick="showPhaseC('${c.governance.case_id}','${id}')">Risks & safeguards</button>`; }
  if(approved){ nextTitle='Operate & monitor'; nextCopy='This AI use has an approved baseline. Monitor performance, fairness, human oversight and governance health, and report material changes or incidents.'; nextButton=`<button class="primary" onclick="showMonitoring('${c.governance.case_id}','${id}')">Open monitoring</button><div style="height:9px"></div><button class="secondary" onclick="showApproval('${c.governance.case_id}','${id}')">View approval</button>`; }
  app.innerHTML=`<div class="detail-grid"><div class="panel"><p class="eyebrow">AI CARD</p><div class="section-title"><div><h2>${esc(c.name)}</h2><p class="muted">${esc(c.purpose)}</p></div><span class="pill ${approved?'good':hasRisk?'good':hasRules?'good':'warn'}">${esc(c.governance.stage)}</span></div>
    <div class="journey">${journey.map(x=>`<div class="journey-step ${x}"></div>`).join('')}</div><div class="journey-labels"><span>Describe</span><span>Rules</span><span>Risks</span><span>Safeguards</span><span>Approve</span><span>Operate</span></div>
    <h3 style="margin-top:28px">What is this AI?</h3><div class="kv"><span>Owner</span><strong>${esc(c.owner)}</strong></div><div class="kv"><span>System</span><span>${esc(c.system.name)} · ${esc(c.system.development_type)}</span></div><div class="kv"><span>Where</span><span>${esc(c.context.countries.join(', '))}</span></div><div class="kv"><span>Affects</span><span>${esc(c.context.affected_population)}</span></div><div class="kv"><span>Decision area</span><span>${esc(c.context.decision_domain)}</span></div><div class="kv"><span>AI role</span><span>${esc(c.context.ai_role)}</span></div>
  </div><div class="panel"><p class="eyebrow">NEXT STEP</p><h2>${nextTitle}</h2><p class="muted">${nextCopy}</p>${nextButton}<div style="height:16px"></div><span class="pill ${c.governance.needs_attention?'warn':'good'}">${c.governance.needs_attention} actions need attention</span></div></div>
  ${approved?renderOperationalSummary(approval,monitoring,c.governance.case_id,id):hasRisk?renderPhaseCSummary(phaseC,c.governance.case_id,id):hasRules?renderRulesAndActions(c.classifications,c.actions,false):''}`;
}

function renderRulesAndActions(profile, actions, detailed=true){
  return `<div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 7"><div class="section-title"><div><p class="eyebrow">REGULATORY PROFILE</p><h2>Rules Check</h2></div></div><div class="profile">${profile.map(p=>`<div class="profile-row"><strong>${esc(labelDimension(p.dimension))}</strong><div><div class="result-main">${esc(labelOutcome(p.outcome))}</div>${p.explanation?`<div class="explain">${esc(p.explanation)}</div>`:''}${p.source?`<div class="source">${esc(p.source)}</div>`:''}</div><span class="pill ${badgeFor(p.outcome)}">${esc(p.confidence||'')}</span></div>`).join('')}</div></div><div class="panel" style="grid-column:span 5"><div class="section-title"><div><p class="eyebrow">WHAT YOU NEED TO DO</p><h2>Governance actions</h2></div></div><div class="actions-list">${actions.length?actions.map(a=>`<div class="action"><div class="priority ${a.priority}"></div><div><h4>${esc(a.title)}</h4><p>${esc(a.description)}</p>${a.source?`<div class="source" style="margin-top:6px">${esc(a.source)}</div>`:''}</div></div>`).join(''):'<p class="muted">No actions generated.</p>'}</div></div></div>`;
}

async function runRules(caseId,id){const r=await api(`/api/governance-cases/${caseId}/rules-check`,{method:'POST'}); app.innerHTML = `<div class="panel"><p class="eyebrow">RULES CHECK COMPLETE</p><h2>We translated the AI use into an explainable regulatory profile.</h2><p class="muted">This prototype intentionally uses screening conclusions such as “review required” where a full legal determination needs more facts or expert confirmation.</p><button class="secondary" onclick="openCard('${id}')">Back to AI card</button></div>`+renderRulesAndActions(r.regulatory_profile,r.actions);}
async function showRules(id){const c=await api(`/api/ai-uses/${id}/card`); /* show latest persisted summary plus action cards */ app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${id}')">← Back to AI card</button><p class="eyebrow" style="margin-top:22px">RULES CHECK</p><h2>${esc(c.name)}</h2><p class="muted">Current persisted regulatory profile. Re-running the rules check creates fresh evaluations in the backend.</p></div>`+renderRulesAndActions(c.classifications,c.actions,false);}


function riskTone(result){ return result==='CRITICAL'?'danger':result==='HIGH'?'warn':result==='LOW'?'good':''; }
function renderPhaseCSummary(p,caseId,aiUseId){
  return `<div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 6"><p class="eyebrow">RISKS & IMPACTS</p><h2>${p.summary.risk_count} risks identified</h2><p class="muted">${p.summary.high_risks} currently rated high or critical. Ratings are reviewable and preserve history.</p><div class="tag-list"><span class="pill ${p.summary.high_risks?'warn':'good'}">${p.summary.high_risks} high</span><span class="pill">${p.assessment_status}</span></div></div><div class="panel" style="grid-column:span 6"><p class="eyebrow">SAFEGUARDS & PROOF</p><h2>${p.summary.safeguards_ready}/${p.summary.safeguard_count} ready</h2><p class="muted">${p.summary.evidence_count} evidence items linked to safeguard implementations.</p><button class="secondary" onclick="showPhaseC('${caseId}','${aiUseId}')">Open workspace</button></div></div>`;
}

async function startRiskReview(caseId,aiUseId){
  const people=await api('/api/people');
  const preferred=people.find(p=>p.authority_level==='GOVERNANCE_APPROVER')||people[0];
  await api(`/api/governance-cases/${caseId}/risk-review/initialize`,{method:'POST',body:JSON.stringify({owner_person_id:preferred?.id||null})});
  await showPhaseC(caseId,aiUseId);
}

async function showPhaseC(caseId,aiUseId){
  const [p,people]=await Promise.all([api(`/api/governance-cases/${caseId}/phase-c`),api('/api/people')]);
  const personOptions=people.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('');
  title.textContent='Risks & safeguards';
  app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${aiUseId}')">← Back to AI card</button><p class="eyebrow" style="margin-top:22px">PHASE C · RISK & ASSURANCE</p><h2>What could go wrong, and what are we doing about it?</h2><p class="muted">Suggested risks are starting points, not automatic truth. Review the rating, then make the safeguards concrete and attach proof.</p></div>
  <div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 7"><div class="section-title"><div><p class="eyebrow">WHAT COULD GO WRONG?</p><h2>Risk & impact review</h2></div><span class="pill">${p.risks.length} risks</span></div><div class="risk-list">${p.risks.map(r=>`<div class="risk-card"><div class="section-title"><div><h3>${esc(r.title)}</h3><div class="source">${esc(r.code)}</div></div><span class="pill ${riskTone(r.evaluation?.result)}">${esc(r.evaluation?.result||'Not rated')}</span></div><div class="risk-chain"><div><small>CAUSE</small><p>${esc(r.cause)}</p></div><div class="arrow">→</div><div><small>EVENT</small><p>${esc(r.event)}</p></div><div class="arrow">→</div><div><small>IMPACT</small><p>${esc(r.consequence)}</p></div></div><div class="risk-footer"><span class="pill">Uncertainty: ${esc(r.evaluation?.uncertainty||'—')}</span><button class="secondary" onclick="reviewRisk('${r.id}','${caseId}','${aiUseId}')">Review rating</button></div></div>`).join('')}</div></div>
  <div class="panel" style="grid-column:span 5"><div class="section-title"><div><p class="eyebrow">SAFEGUARDS</p><h2>What are we doing about it?</h2></div><span class="pill ${p.summary.safeguards_ready===p.summary.safeguard_count?'good':'warn'}">${p.summary.safeguards_ready}/${p.summary.safeguard_count} ready</span></div><div class="safeguards">${p.safeguards.map(s=>`<div class="safeguard"><div class="section-title"><div><strong>${esc(s.name)}</strong><div class="source">${esc(s.control_code)}</div></div><span class="pill ${s.status==='IMPLEMENTED'||s.status==='EFFECTIVE'?'good':'warn'}">${esc(s.status)}</span></div><p class="muted">${esc(s.description)}</p><div class="safeguard-actions"><button class="secondary" onclick="markSafeguard('${s.id}','IMPLEMENTED','${caseId}','${aiUseId}')">Mark implemented</button><button class="secondary" onclick="openEvidenceModal('${s.id}','${caseId}','${aiUseId}')">+ Proof</button></div>${s.evidence.length?`<div class="evidence-list">${s.evidence.map(e=>`<div class="evidence-item">✓ <strong>${esc(e.title)}</strong><span>${esc(e.type)}</span></div>`).join('')}</div>`:`<div class="no-proof">No proof linked yet</div>`}</div>`).join('')}</div></div></div>`;
}

async function reviewRisk(riskId,caseId,aiUseId){
  const rating=prompt('Risk rating: LOW, MEDIUM, HIGH or CRITICAL','HIGH'); if(!rating)return;
  const uncertainty=prompt('Uncertainty: LOW, MEDIUM or HIGH','MEDIUM'); if(!uncertainty)return;
  const rationale=prompt('Why did you choose this rating?','Reviewed against the current deployment context.');
  try{await api(`/api/risks/${riskId}/evaluation`,{method:'POST',body:JSON.stringify({result:rating.toUpperCase(),uncertainty:uncertainty.toUpperCase(),rationale})});await showPhaseC(caseId,aiUseId)}catch(e){alert(e.message)}
}
async function markSafeguard(id,status,caseId,aiUseId){try{await api(`/api/control-implementations/${id}`,{method:'PATCH',body:JSON.stringify({status})});await showPhaseC(caseId,aiUseId)}catch(e){alert(e.message)}}
function openEvidenceModal(id,caseId,aiUseId){
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(620px,96vw)"><div class="modal-head"><div><p class="eyebrow">HOW DO WE KNOW?</p><h2>Add proof</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body"><div class="field"><label>Evidence title</label><input id="ev-title" placeholder="e.g. Human oversight procedure v2"></div><div class="field"><label>Evidence type</label><select id="ev-type"><option>PROCEDURE</option><option>TRAINING_RECORD</option><option>TEST_REPORT</option><option>SYSTEM_CONFIGURATION</option><option>POLICY</option><option>CONTRACT</option><option>ATTESTATION</option><option>OTHER</option></select></div><div class="field"><label>Reference</label><input id="ev-ref" placeholder="File path, document ID or link"></div><div class="field"><label>Valid until</label><input id="ev-until" type="date"></div></div><div class="modal-footer"><button class="secondary" onclick="closeWizard()">Cancel</button><button class="primary" id="save-evidence">Add proof</button></div></div></div>`;
  document.getElementById('save-evidence').onclick=async()=>{try{await api(`/api/control-implementations/${id}/evidence`,{method:'POST',body:JSON.stringify({title:document.getElementById('ev-title').value.trim(),evidence_type:document.getElementById('ev-type').value,artifact_reference:document.getElementById('ev-ref').value.trim()||null,valid_until:document.getElementById('ev-until').value||null})});closeWizard();await showPhaseC(caseId,aiUseId)}catch(e){alert(e.message)}};
}

async function renderPeople(){
  navActive('people'); title.textContent='People & competence';
  const [people,countries,groups,learning]=await Promise.all([api('/api/people'),api('/api/reference/countries'),api('/api/groups'),api('/api/learning/dashboard')]);
  const countryMap=Object.fromEntries(countries.map(c=>[c.code,c.name])); const readiness=Object.fromEntries(learning.people.map(x=>[x.person_id,x]));
  app.innerHTML=`<div class="grid"><div class="panel" style="grid-column:span 12"><div class="section-title"><div><p class="eyebrow">PEOPLE, ROLES & COMPETENCE</p><h2>People inventory</h2><p class="muted">People are maintained once. Governance roles are dynamic assignments; role-specific training determines readiness.</p></div><button class="primary" onclick="openPersonModal()">+ Add person</button></div>
  <div class="directory">${people.map(p=>{const r=readiness[p.id]||{roles:[],training:{ready:true,missing_mandatory:[]}};return `<div class="person-row"><div><div class="person-name">${esc(p.display_name)}</div><div class="person-sub">${esc(p.email||'No email')}</div></div><div><strong>${esc(p.job_title||'No job title')}</strong><div class="person-sub">${esc(countryMap[p.country_code]||p.country_code||'—')}</div></div><div class="tag-list">${r.roles.map(x=>`<span class="tag">${esc(x)}</span>`).join('')||'<span class="muted">No governance role</span>'}</div><div><span class="pill ${r.training.ready?'good':'warn'}">${r.training.ready?'Training current':r.training.missing_mandatory.length+' gap(s)'}</span></div><div class="tag-list">${(p.qualifications||[]).map(q=>`<span class="tag">${esc(q.type)}</span>`).join('')}</div></div>`}).join('')}</div></div>
  <div class="panel" style="grid-column:span 7"><p class="eyebrow">TRAINING READINESS</p><h2>${learning.people_ready}/${learning.people.length} people current</h2>${learning.courses.map(c=>`<div class="kv"><span>${esc(c.course)}</span><span>${c.assigned?`${c.current}/${c.assigned} current · ${c.coverage}%`:'No role requirement assigned'}</span></div>`).join('')}</div>
  <div class="panel" style="grid-column:span 5"><p class="eyebrow">GROUPS</p><h2>Teams & committees</h2>${groups.map(g=>`<div class="ai-card"><strong>${esc(g.name)}</strong><div class="person-sub">${esc(g.group_type)} · ${esc(g.description||'')}</div></div>`).join('')}</div></div>`;
}

async function openPersonModal(){
  const [countries,businessUnits,people]=await Promise.all([api('/api/reference/countries'),api('/api/business-units'),api('/api/people')]);
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">PEOPLE INVENTORY</p><h2>Add person</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body">
  <div class="choice-grid"><div class="field"><label>First name</label><input id="p-first"></div><div class="field"><label>Last name</label><input id="p-last"></div></div>
  <div class="field"><label>Email</label><input id="p-email" type="email"></div>
  <div class="choice-grid"><div class="field"><label>Job title</label><input id="p-title"></div><div class="field"><label>Employee ID</label><input id="p-employee"></div></div>
  <div class="choice-grid"><div class="field"><label>Business unit</label><select id="p-bu">${businessUnits.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Country</label><select id="p-country"><option value="">Select country</option>${countries.map(c=>`<option value="${c.code}">${esc(c.name)} (${c.code})</option>`).join('')}</select></div></div>
  <div class="choice-grid"><div class="field"><label>Manager</label><select id="p-manager"><option value="">No manager / unknown</option>${people.map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}</select></div><div class="field"><label>Authority level</label><select id="p-authority"><option value="">Not specified</option><option>INDIVIDUAL_CONTRIBUTOR</option><option>MANAGER</option><option>EXECUTIVE</option><option>GOVERNANCE_APPROVER</option></select></div></div>
  </div><div class="modal-footer"><button class="secondary" onclick="closeWizard()">Cancel</button><button class="primary" id="save-person">Add person</button></div></div></div>`;
  document.getElementById('save-person').onclick=async()=>{try{await api('/api/people',{method:'POST',body:JSON.stringify({first_name:document.getElementById('p-first').value.trim(),last_name:document.getElementById('p-last').value.trim(),email:document.getElementById('p-email').value.trim()||null,employee_id:document.getElementById('p-employee').value.trim()||null,job_title:document.getElementById('p-title').value.trim()||null,employment_type:'EMPLOYEE',business_unit_id:document.getElementById('p-bu').value||null,manager_person_id:document.getElementById('p-manager').value||null,country_code:document.getElementById('p-country').value||null,authority_level:document.getElementById('p-authority').value||null})});closeWizard();await renderPeople()}catch(e){alert(e.message)}};
}

async function openWizard(){
 const [people,countries]=await Promise.all([api('/api/people'),api('/api/reference/countries')]);
 if(!people.length){alert('Add at least one person to the People inventory before creating an AI use.'); await renderPeople(); return;}
 const data={step:0};
 const defaultOwner=people[0];
 const euPreferred=['FR','DE'];
 const steps=[
  {title:'What are you using AI for?',html:()=>`<div class="field"><label>Name this AI use</label><input id="f-name" value="Candidate screening" /></div><div class="field"><label>What are you trying to achieve?</label><textarea id="f-purpose">Help recruiters identify candidates whose experience matches job requirements.</textarea><small>We use this to understand the intended business purpose — you do not need legal terminology.</small></div><div class="field"><label>Business process</label><select id="f-process"><option>Recruitment</option><option>Customer service</option><option>Finance</option><option>Operations</option><option>Other</option></select></div><div class="field"><label>Business owner</label><select id="f-owner">${people.map(p=>`<option value="${p.id}" ${p.id===defaultOwner.id?'selected':''}>${esc(p.display_name)}${p.job_title?' — '+esc(p.job_title):''}</option>`).join('')}</select><small>Owners come from the People inventory so governance responsibilities stay consistent.</small></div>`,save:()=>Object.assign(data,{name:v('f-name'),business_purpose:v('f-purpose'),business_process:v('f-process'),owner_person_id:v('f-owner')})},
  {title:'What AI solution is involved?',html:()=>`<div class="field"><label>System or product name</label><input id="f-system" value="TalentAI" /></div><div class="field"><label>What is the system intended to do?</label><textarea id="f-syspurpose">Rank job applicants for recruiter review.</textarea></div><div class="field"><label>How is it supplied?</label><select id="f-supply"><option value="third_party">A product supplied by another company</option><option value="internal">Built internally</option><option value="hybrid">Combination of internal and external</option><option value="unknown">I don't know</option></select></div><div class="field"><label>Supplier</label><input id="f-supplier" value="TalentAI Vendor" /></div>`,save:()=>Object.assign(data,{system_name:v('f-system'),system_purpose:v('f-syspurpose'),supply_model:v('f-supply'),supplier_name:v('f-supplier')||null})},
  {title:'How does the AI influence decisions?',html:()=>`<div class="field"><label>What does the AI do?</label><select id="f-function"><option value="ranking">Rank people or options</option><option value="scoring">Score something</option><option value="selection">Select/filter</option><option value="evaluation">Evaluate</option><option value="generation">Generate content</option><option value="chatbot">Interact with people</option></select><small>This helps the Rules Check classify the use — you do not need to know the legal category.</small></div><div class="field"><label>Which decision area is involved?</label><select id="f-domain"><option value="employment">Employment / recruitment</option><option value="education">Education</option><option value="credit">Credit / financial services</option><option value="healthcare">Healthcare</option><option value="other">Other</option></select></div><div class="field"><label>Who makes the final decision?</label><select id="f-human"><option value="true">A person makes the final decision</option><option value="false">The AI can make/execute the final decision</option></select></div>`,save:()=>Object.assign(data,{function:v('f-function'),decision_domain:v('f-domain'),human_final_decision:v('f-human')==='true'})},
  {title:'Who could be affected, and where?',html:()=>`<div class="field"><label>Who could be affected?</label><select id="f-pop"><option value="job_applicants">Job applicants</option><option value="employees">Employees</option><option value="customers">Customers</option><option value="patients">Patients</option><option value="students">Students</option><option value="general_public">General public</option></select></div><div class="field"><label>Countries</label><select id="f-countries" class="country-select" multiple>${countries.map(c=>`<option value="${c.code}" ${euPreferred.includes(c.code)?'selected':''}>${esc(c.name)} (${c.code})${c.eu_member?' · EU':''}</option>`).join('')}</select><small>Select one or more countries from the ISO 3166-1 directory. Hold Ctrl/Cmd to select multiple countries.</small></div>`,save:()=>Object.assign(data,{affected_population:v('f-pop'),countries:[...document.getElementById('f-countries').selectedOptions].map(o=>o.value)})},
  {title:'Review your AI use',html:()=>`<div class="panel" style="box-shadow:none;padding:18px"><p class="eyebrow">AI USE SUMMARY</p><h2>${esc(data.name)}</h2><p>${esc(data.business_purpose)}</p><div class="kv"><span>Business owner</span><span>${esc((people.find(p=>p.id===data.owner_person_id)||{}).display_name||'')}</span></div><div class="kv"><span>System</span><span>${esc(data.system_name)}</span></div><div class="kv"><span>Supply</span><span>${esc(data.supply_model)}</span></div><div class="kv"><span>Function</span><span>${esc(data.function)}</span></div><div class="kv"><span>Decision area</span><span>${esc(data.decision_domain)}</span></div><div class="kv"><span>Affected people</span><span>${esc(data.affected_population)}</span></div><div class="kv"><span>Countries</span><span>${esc(data.countries.map(code=>(countries.find(c=>c.code===code)||{name:code}).name).join(', '))}</span></div></div><p class="muted">Behind the scenes this creates linked inventory records using controlled people and country references.</p>`,save:()=>{}},
 ];
 function v(id){return document.getElementById(id).value.trim()}
 function draw(){const s=steps[data.step];modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ADD AI USE · ${data.step+1} OF ${steps.length}</p><h2>${s.title}</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body"><div class="steps">${steps.map((_,i)=>`<div class="step-dot ${i<data.step?'done':i===data.step?'active':''}"></div>`).join('')}</div>${s.html()}</div><div class="modal-footer"><button class="secondary" id="back" ${data.step===0?'disabled':''}>Back</button><button class="primary" id="next">${data.step===steps.length-1?'Create AI use':'Continue'}</button></div></div></div>`;document.getElementById('back').onclick=()=>{if(data.step){data.step--;draw()}};document.getElementById('next').onclick=async()=>{s.save();if(data.step===3&&!data.countries.length){alert('Select at least one country.');return;}if(data.step<steps.length-1){data.step++;draw()}else{try{const created=await api('/api/ai-uses',{method:'POST',body:JSON.stringify(data)});closeWizard();await openCard(created.ai_use_id)}catch(e){alert(e.message)}}};}
 draw();
}
function closeWizard(){modalRoot.innerHTML=''}

async function renderGovernance(){
  navActive('governance'); title.textContent='Governance';
  const [roles,responsibilities,learning]=await Promise.all([api('/api/governance/roles'),api('/api/governance/responsibilities'),api('/api/learning/dashboard')]);
  const stages=['DESCRIBE','RULES','RISKS','SAFEGUARDS','APPROVAL','OPERATE'];
  app.innerHTML=`<div class="grid"><div class="panel hero"><p class="eyebrow">ORGANISATION GOVERNANCE</p><h2>The management system above every AI use</h2><p class="muted">This area defines who is accountable, how responsibilities are allocated, and which competence is required. It complements the per-AI journey in My AI.</p><div class="stat-grid"><div class="stat"><strong>${roles.length}</strong><span>Governance roles</span></div><div class="stat"><strong>${responsibilities.length}</strong><span>Responsibilities</span></div><div class="stat"><strong>${learning.roles}</strong><span>Roles with learning profiles</span></div><div class="stat"><strong>${learning.people_with_gaps}</strong><span>People with training gaps</span></div></div></div>
  <div class="panel side-panel"><p class="eyebrow">TWO LEVELS</p><h2>Governance ≠ one AI workflow</h2><p class="muted"><strong>Governance</strong> defines the organisation-wide system. <strong>My AI</strong> applies it to a specific AI use.</p></div>
  <div class="panel" style="grid-column:span 12"><p class="eyebrow">RACI</p><h2>Dynamic role model</h2><div class="raci-wrap"><table class="raci"><thead><tr><th>Responsibility</th>${roles.map(r=>`<th>${esc(r.name)}</th>`).join('')}</tr></thead><tbody>${responsibilities.map(resp=>`<tr><td><strong>${esc(resp.name)}</strong><div class="person-sub">${esc(resp.lifecycle_stage||'')}</div></td>${roles.map(role=>{const x=role.responsibilities.find(rr=>rr.responsibility_id===resp.id);return `<td>${x?`<span class="raci-chip">${esc(x.raci[0])}</span>`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">R = Responsible · A = Accountable · C = Consulted · I = Informed. The matrix is attached to roles, never directly to physical people.</p></div>
  <div class="panel" style="grid-column:span 12"><p class="eyebrow">ROLE-BASED LEARNING</p><h2>Training profiles</h2><div class="ai-list">${roles.map(r=>`<div class="ai-card"><div class="section-title"><div><h3>${esc(r.name)}</h3><p class="muted">${esc(r.description||'')}</p></div><span class="pill">${r.training_requirements.length} training requirements</span></div><div class="tag-list">${r.training_requirements.map(t=>`<span class="tag">${esc(t.course)} · ${esc(t.requirement_level)}</span>`).join('')||'<span class="muted">No training configured</span>'}</div></div>`).join('')}</div></div></div>`;
}

async function renderGuide(){
  navActive('guide'); title.textContent='AI Governance Guide'; const items=await api('/api/guide');
  const understand=items.filter(x=>x.section==='UNDERSTAND'), journey=items.filter(x=>x.section==='JOURNEY');
  app.innerHTML=`<div class="grid"><div class="panel hero"><p class="eyebrow">START HERE</p><h2>Understand AI governance before completing governance tasks</h2><p class="muted">The guide explains the whole management system and every step we ask users to perform. The same content can later power contextual “Why are we asking this?” help.</p></div><div class="panel side-panel"><p class="eyebrow">PRINCIPLE</p><h2>Business language first</h2><p class="muted">Users provide facts and decisions. Legal and governance interpretation remains traceable behind the interface.</p></div>
  <div class="panel" style="grid-column:span 12"><p class="eyebrow">UNDERSTAND THE SYSTEM</p><h2>AI governance in its totality</h2><div class="guide-grid">${understand.map(x=>guideCard(x)).join('')}</div></div>
  <div class="panel" style="grid-column:span 12"><p class="eyebrow">GOVERN ONE AI USE</p><h2>The guided journey</h2><div class="guide-grid">${journey.map(x=>guideCard(x)).join('')}</div></div></div>`;
}
function guideCard(x){return `<article class="guide-card"><div class="section-title"><h3>${esc(x.title)}</h3>${x.journey_stage?`<span class="pill">${esc(x.journey_stage)}</span>`:''}</div><p>${esc(x.summary)}</p>${x.why_it_matters?`<p><strong>Why it matters</strong><br><span class="muted">${esc(x.why_it_matters)}</span></p>`:''}${x.expected_input?`<p><strong>What we need</strong><br><span class="muted">${esc(x.expected_input)}</span></p>`:''}${x.responsible_role?`<p><strong>Typical contributor</strong><br><span class="muted">${esc(x.responsible_role)}</span></p>`:''}<div class="source">${esc(x.source_reference||'')}</div></article>`}
window.renderGovernance=renderGovernance;window.renderGuide=renderGuide;

window.openWizard=openWizard;window.closeWizard=closeWizard;window.renderPortfolio=renderPortfolio;window.openCard=openCard;window.runRules=runRules;window.showRules=showRules;window.renderPeople=renderPeople;window.openPersonModal=openPersonModal;window.startRiskReview=startRiskReview;window.showPhaseC=showPhaseC;window.reviewRisk=reviewRisk;window.markSafeguard=markSafeguard;window.openEvidenceModal=openEvidenceModal;

document.getElementById('new-ai').onclick=openWizard;
document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>({home:renderHome,portfolio:renderPortfolio,actions:renderActions,people:renderPeople,monitor:renderMonitor,governance:renderGovernance,guide:renderGuide}[b.dataset.view]||renderHome)());
renderHome().catch(e=>{app.innerHTML=`<div class="panel"><h2>Backend not reachable</h2><p class="muted">Start the FastAPI backend on port 8000, then refresh.</p><pre>${esc(e.message)}</pre></div>`});

function renderOperationalSummary(approval,monitoring,caseId,aiUseId){
  const breaches=(monitoring?.events||[]).filter(e=>e.type==='MONITORING_BREACH'&&e.status==='OPEN').length;
  return `<div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 6"><p class="eyebrow">APPROVAL</p><h2>${esc(labelOutcome(approval.decision?.outcome||'Not approved'))}</h2><p class="muted">Approved by ${esc(approval.decision?.authority||'—')} · frozen baseline ${approval.baseline?'created':'missing'}.</p><button class="secondary" onclick="showApproval('${caseId}','${aiUseId}')">View approval</button></div><div class="panel" style="grid-column:span 6"><p class="eyebrow">OPERATIONS</p><h2>${breaches?'Needs review':'Monitoring active'}</h2><p class="muted">${monitoring?.definitions?.length||0} monitoring checks · ${breaches} open threshold breaches.</p><button class="secondary" onclick="showMonitoring('${caseId}','${aiUseId}')">Open monitoring</button></div></div>`;
}

async function showApproval(caseId,aiUseId){
  const [a,people]=await Promise.all([api(`/api/governance-cases/${caseId}/approval`),api('/api/people')]);
  title.textContent='Approval';
  const eligible=people.filter(p=>p.authority_level==='GOVERNANCE_APPROVER'||(p.qualifications||[]).some(q=>q.type==='AI_GOVERNANCE_REVIEWER'));
  const decision=a.decision;
  app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${aiUseId}')">← Back to AI card</button><p class="eyebrow" style="margin-top:22px">PHASE D · APPROVAL</p><h2>Can this AI move into controlled operation?</h2><p class="muted">Approval freezes the current regulatory, risk, safeguard and evidence state into an auditable baseline.</p></div>
  <div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 7"><p class="eyebrow">G07 · APPROVAL READINESS</p><h2>${a.readiness.ready?'Ready for decision':'Not ready yet'}</h2>${a.readiness.blockers.length?`<div class="actions-list">${a.readiness.blockers.map(b=>`<div class="action"><div class="priority HIGH"></div><div><h4>Approval blocker</h4><p>${esc(b)}</p></div></div>`).join('')}</div>`:`<div class="evidence-item">✓ Risk review complete</div><div class="evidence-item">✓ Safeguards implemented</div><div class="evidence-item">✓ Supporting proof attached</div>`}</div>
  <div class="panel" style="grid-column:span 5"><p class="eyebrow">ACCOUNTABLE DECISION</p>${decision?`<h2>${esc(labelOutcome(decision.outcome))}</h2><div class="kv"><span>Authority</span><strong>${esc(decision.authority)}</strong></div><div class="kv"><span>Decided</span><span>${esc(new Date(decision.decided_at).toLocaleString())}</span></div><div class="kv"><span>Rationale</span><span>${esc(decision.rationale||'—')}</span></div><div class="kv"><span>Baseline</span><span>${a.baseline?esc(a.baseline.content_hash.slice(0,12))+'…':'—'}</span></div>`:`<h2>Decision required</h2><div class="field"><label>Approver</label><select id="approval-authority">${eligible.map(p=>`<option value="${p.id}">${esc(p.display_name)} · ${esc(p.job_title||'')}</option>`).join('')}</select></div><div class="field"><label>Rationale</label><textarea id="approval-rationale" rows="4" placeholder="Why is this AI ready, or why should approval be deferred?"></textarea></div><div class="field"><label>Conditions (optional)</label><input id="approval-conditions" placeholder="e.g. Quarterly fairness review; human final decision"></div><div class="safeguard-actions"><button class="primary" ${a.readiness.ready&&eligible.length?'':'disabled'} onclick="decideApproval('${caseId}','${aiUseId}','APPROVED')">Approve</button><button class="secondary" ${eligible.length?'':'disabled'} onclick="decideApproval('${caseId}','${aiUseId}','DEFERRED')">Request changes</button></div>${!eligible.length?'<p class="muted">No eligible governance approver is available in the People inventory.</p>':''}`}</div></div>`;
}

async function decideApproval(caseId,aiUseId,outcome){
  const authority=document.getElementById('approval-authority')?.value; if(!authority)return alert('Select an approver.');
  const rationale=document.getElementById('approval-rationale')?.value.trim()||null;
  const conditions=(document.getElementById('approval-conditions')?.value||'').split(';').map(x=>x.trim()).filter(Boolean);
  try{await api(`/api/governance-cases/${caseId}/approval`,{method:'POST',body:JSON.stringify({decision_authority_id:authority,outcome,rationale,conditions})});await showApproval(caseId,aiUseId)}catch(e){alert(e.message)}
}

async function showMonitoring(caseId,aiUseId){
  const m=await api(`/api/governance-cases/${caseId}/monitoring`); title.textContent='Monitor'; navActive('monitor');
  if(!m.active){app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${aiUseId}')">← Back</button><div class="empty"><h2>Monitoring starts after approval</h2><p class="muted">Approve this AI use first to create its operational monitoring plan.</p></div></div>`;return;}
  app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${aiUseId}')">← Back to AI card</button><p class="eyebrow" style="margin-top:22px">OPERATIONS</p><h2>Is this AI still operating within its approved conditions?</h2><p class="muted">Monitoring is connected to the approved deployment. Breaches, changes and incidents can trigger reassessment.</p></div>
  <div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 7"><div class="section-title"><div><p class="eyebrow">WHAT WE WATCH</p><h2>Monitoring plan</h2></div><span class="pill good">ACTIVE</span></div><div class="monitor-list">${m.definitions.map(d=>`<div class="monitor-row"><div><strong>${esc(d.name)}</strong><p class="muted">${esc(d.description||'')}</p><span class="pill">${esc(d.frequency)}</span></div><div>${d.latest?`<span class="pill ${d.latest.threshold_status==='BREACH'?'danger':'good'}">${esc(d.latest.threshold_status)}</span><div class="person-sub">${esc(d.latest.qualitative_result||JSON.stringify(d.latest.value||{}))}</div>`:'<span class="pill warn">No observation</span>'}<div style="height:8px"></div><button class="secondary" onclick="recordObservation('${d.id}','${caseId}','${aiUseId}')">Record result</button></div></div>`).join('')}</div></div>
  <div class="panel" style="grid-column:span 5"><p class="eyebrow">REPORT SOMETHING</p><h2>Change or issue?</h2><p class="muted">Material changes and incidents create a traceable governance event and can reopen review automatically.</p><button class="secondary" onclick="openChangeModal('${caseId}','${aiUseId}')">Report change</button><div style="height:9px"></div><button class="secondary" onclick="openIncidentModal('${caseId}','${aiUseId}')">Report incident</button></div>
  <div class="panel" style="grid-column:span 12"><div class="section-title"><div><p class="eyebrow">HISTORY</p><h2>Events & reassessments</h2></div></div>${m.events.length?m.events.map(e=>`<div class="event-row"><div><strong>${esc(e.type.replaceAll('_',' '))}</strong><p class="muted">${esc(e.description)}</p></div><span class="pill ${e.severity==='CRITICAL'?'danger':e.severity==='HIGH'?'warn':''}">${esc(e.severity)}</span></div>`).join(''):'<p class="muted">No operational events recorded.</p>'}${m.reassessments.length?`<h3>Open reassessments</h3>${m.reassessments.map(r=>`<div class="event-row"><div><strong>Review from ${esc(r.starting_domain)}</strong><p class="muted">${esc(r.reason)}</p></div><span class="pill warn">${esc(r.status)}</span></div>`).join('')}`:''}</div></div>`;
}

async function recordObservation(definitionId,caseId,aiUseId){
  const result=prompt('Result: enter PASS/FAIL or a short qualitative observation','PASS'); if(result===null)return;
  try{await api(`/api/monitoring-definitions/${definitionId}/observations`,{method:'POST',body:JSON.stringify({qualitative_result:result})});await showMonitoring(caseId,aiUseId)}catch(e){alert(e.message)}
}

function openChangeModal(caseId,aiUseId){
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">CHANGE</p><h2>What changed?</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body"><div class="field"><label>Change type</label><select id="chg-type"><option>MODEL_VERSION</option><option>INTENDED_PURPOSE</option><option>DATA_SOURCE</option><option>GEOGRAPHY</option><option>AFFECTED_POPULATION</option><option>AUTOMATION_LEVEL</option><option>HUMAN_OVERSIGHT</option><option>VENDOR</option><option>CONFIGURATION</option></select></div><div class="field"><label>What changed?</label><textarea id="chg-desc" rows="4"></textarea></div><div class="field"><label>Materiality</label><select id="chg-mat"><option>UNDETERMINED</option><option>NON_MATERIAL</option><option>MATERIAL</option><option>POTENTIALLY_SUBSTANTIAL</option><option>SUBSTANTIAL</option></select><small>“Substantial” can have legal significance and requires governance confirmation; this field is a prototype assessment input.</small></div></div><div class="modal-footer"><button class="secondary" onclick="closeWizard()">Cancel</button><button class="primary" id="save-change">Report change</button></div></div></div>`;
  document.getElementById('save-change').onclick=async()=>{try{await api(`/api/governance-cases/${caseId}/changes`,{method:'POST',body:JSON.stringify({change_type:document.getElementById('chg-type').value,description:document.getElementById('chg-desc').value.trim(),materiality:document.getElementById('chg-mat').value})});closeWizard();await showMonitoring(caseId,aiUseId)}catch(e){alert(e.message)}};
}

function openIncidentModal(caseId,aiUseId){
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">INCIDENT</p><h2>Report an AI issue</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body"><div class="field"><label>Category</label><select id="inc-cat"><option>PERFORMANCE</option><option>FAIRNESS</option><option>HUMAN_OVERSIGHT_FAILURE</option><option>SECURITY</option><option>PRIVACY</option><option>SAFETY</option><option>FUNDAMENTAL_RIGHTS</option><option>MISUSE</option><option>OTHER</option></select></div><div class="field"><label>What happened?</label><textarea id="inc-desc" rows="4"></textarea></div><div class="field"><label>Operational severity</label><select id="inc-sev"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><small>Operational severity is separate from the EU AI Act legal classification of a serious incident.</small></div></div><div class="modal-footer"><button class="secondary" onclick="closeWizard()">Cancel</button><button class="primary" id="save-incident">Report incident</button></div></div></div>`;
  document.getElementById('save-incident').onclick=async()=>{try{await api(`/api/governance-cases/${caseId}/incidents`,{method:'POST',body:JSON.stringify({incident_category:document.getElementById('inc-cat').value,description:document.getElementById('inc-desc').value.trim(),severity:document.getElementById('inc-sev').value})});closeWizard();await showMonitoring(caseId,aiUseId)}catch(e){alert(e.message)}};
}

async function renderMonitor(){
  navActive('monitor'); title.textContent='Monitor'; await loadUses();
  let rows=[]; for(const u of uses){try{const c=await api(`/api/ai-uses/${u.id}/card`);const m=await api(`/api/governance-cases/${c.governance.case_id}/monitoring`);if(m.active)rows.push({use:u,card:c,monitor:m})}catch{}}
  app.innerHTML=`<div class="panel"><div class="section-title"><div><p class="eyebrow">OPERATIONS</p><h2>Active AI monitoring</h2></div></div>${rows.length?`<div class="ai-list">${rows.map(r=>`<div class="ai-card" onclick="showMonitoring('${r.card.governance.case_id}','${r.use.id}')"><div class="section-title"><div><h3>${esc(r.use.name)}</h3><p class="muted">${r.monitor.definitions.length} monitoring checks</p></div><span class="pill ${r.monitor.reassessments.length?'warn':'good'}">${r.monitor.reassessments.length?'Review required':'Healthy'}</span></div></div>`).join('')}</div>`:'<div class="empty"><h2>No approved AI uses yet</h2><p class="muted">Monitoring starts automatically when an AI use is approved.</p></div>'}</div>`;
}
window.showApproval=showApproval;window.decideApproval=decideApproval;window.showMonitoring=showMonitoring;window.recordObservation=recordObservation;window.openChangeModal=openChangeModal;window.openIncidentModal=openIncidentModal;window.renderMonitor=renderMonitor;
