const API = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? 'http://localhost:8000' : 'http://backend:8000';
const app = document.getElementById('app');
const modalRoot = document.getElementById('modal-root');
const title = document.getElementById('page-title');
let uses = [];

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path, opts={}) { const r = await fetch(API + path, {headers:{'Content-Type':'application/json'}, ...opts}); if(!r.ok) throw new Error((await r.json()).detail || r.statusText); return r.json(); }

function badgeFor(outcome){
  if(/APPLICABLE|DEPLOYER/.test(outcome) && !/REVIEW/.test(outcome)) return 'good';
  if(/REVIEW|UNDETERMINED/.test(outcome)) return 'warn';
  return '';
}
function labelDimension(d){return ({REGULATORY_SCOPE:'EU AI Act scope',ACTOR_ROLE:'Your role',HIGH_RISK:'High-risk rules',TRANSPARENCY:'Transparency'})[d]||d.replaceAll('_',' ')}
function labelOutcome(o){return o.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}

async function loadUses(){ uses = await api('/api/ai-uses'); }
function navActive(view){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}

async function renderHome(){
  navActive('home'); title.textContent='Overview'; await loadUses();
  app.innerHTML=`<div class="grid">
    <div class="panel hero"><p class="eyebrow">GOVERNANCE AT A GLANCE</p><h2>${uses.length ? 'Your AI portfolio is taking shape.' : 'Start with the AI your teams actually use.'}</h2><p class="muted">The center translates simple business facts into rules, risks, safeguards and actions — without asking users to interpret the law themselves.</p>
      <div class="stat-grid"><div class="stat"><strong>${uses.length}</strong><span>AI uses</span></div><div class="stat"><strong>${uses.length}</strong><span>Open governance cases</span></div><div class="stat"><strong>${uses.length ? '1+' : '0'}</strong><span>Rules checks</span></div><div class="stat"><strong>${uses.length ? 'Active' : 'Ready'}</strong><span>Prototype status</span></div></div>
    </div>
    <div class="panel side-panel"><p class="eyebrow">HOW IT WORKS</p><h2>One guided journey</h2><div class="journey">${['done','active','','','',''].map(x=>`<div class="journey-step ${x}"></div>`).join('')}</div><div class="journey-labels"><span>Your AI</span><span>Rules</span><span>Risks</span><span>Safeguards</span><span>Approve</span><span>Monitor</span></div><p class="muted" style="margin-top:18px">We are currently implementing the first two stages end-to-end.</p></div>
    <div class="panel" style="grid-column:span 12"><div class="section-title"><h2>Recent AI uses</h2><button class="secondary" onclick="renderPortfolio()">View portfolio</button></div>${renderUseList(uses)}</div>
  </div>`;
}

function renderUseList(items){
  if(!items.length) return `<div class="empty"><div class="icon">◎</div><h2>No AI uses yet</h2><p class="muted">Add a use in business language. The governance model is created behind the scenes.</p><button class="primary" onclick="openWizard()">Add your first AI use</button></div>`;
  return `<div class="ai-list">${items.map(u=>`<div class="ai-card" onclick="openCard('${u.id}')"><div class="section-title"><div><p class="eyebrow">AI USE</p><h3>${esc(u.name)}</h3></div><span class="pill warn">${esc(u.status)}</span></div><p class="muted">${esc(u.purpose)}</p><div class="card-meta"><span class="pill good">Rules check available</span><span class="pill">Governance case</span></div></div>`).join('')}</div>`;
}

async function renderPortfolio(){navActive('portfolio'); title.textContent='My AI'; await loadUses(); app.innerHTML=`<div class="panel"><div class="section-title"><div><p class="eyebrow">AI PORTFOLIO</p><h2>AI uses</h2></div><button class="primary" onclick="openWizard()">+ Add AI use</button></div>${renderUseList(uses)}</div>`;}
async function renderActions(){navActive('actions'); title.textContent='My work'; await loadUses(); let cards=[]; for(const u of uses){try{cards.push(await api(`/api/ai-uses/${u.id}/card`))}catch{}} const actions=cards.flatMap(c=>(c.actions||[]).map(a=>({...a,ai:c.name}))); app.innerHTML=`<div class="panel"><div class="section-title"><div><p class="eyebrow">YOUR WORK</p><h2>Open actions</h2></div></div>${actions.length?`<div class="actions-list">${actions.map(a=>`<div class="action"><div class="priority ${a.priority}"></div><div><h4>${esc(a.title)}</h4><p>${esc(a.ai)} · ${esc(a.description)}</p></div><span class="pill ${a.priority==='HIGH'?'warn':''}">${esc(a.priority)}</span></div>`).join('')}</div>`:`<div class="empty"><h2>No generated actions yet</h2><p class="muted">Run a Rules Check on an AI use to generate governance work.</p></div>`}</div>`;}

async function openCard(id){
  const c=await api(`/api/ai-uses/${id}/card`); navActive('portfolio'); title.textContent=c.name;
  const hasRules=c.classifications.length>0;
  app.innerHTML=`<div class="detail-grid"><div class="panel"><p class="eyebrow">AI CARD</p><div class="section-title"><div><h2>${esc(c.name)}</h2><p class="muted">${esc(c.purpose)}</p></div><span class="pill ${hasRules?'good':'warn'}">${esc(c.governance.stage)}</span></div>
    <div class="journey">${['done',hasRules?'done':'active','','','',''].map(x=>`<div class="journey-step ${x}"></div>`).join('')}</div><div class="journey-labels"><span>Describe</span><span>Rules</span><span>Risks</span><span>Safeguards</span><span>Approve</span><span>Monitor</span></div>
    <h3 style="margin-top:28px">What is this AI?</h3><div class="kv"><span>Owner</span><strong>${esc(c.owner)}</strong></div><div class="kv"><span>System</span><span>${esc(c.system.name)} · ${esc(c.system.development_type)}</span></div><div class="kv"><span>Where</span><span>${esc(c.context.countries.join(', '))}</span></div><div class="kv"><span>Affects</span><span>${esc(c.context.affected_population)}</span></div><div class="kv"><span>Decision area</span><span>${esc(c.context.decision_domain)}</span></div><div class="kv"><span>AI role</span><span>${esc(c.context.ai_role)}</span></div>
  </div><div class="panel"><p class="eyebrow">NEXT STEP</p><h2>${hasRules?'Rules checked':'Run the Rules Check'}</h2><p class="muted">${hasRules?'Review the regulatory profile and actions below.':'We will use the facts you supplied to screen scope, actor role and key EU AI Act classification dimensions.'}</p>${hasRules?`<button class="primary" onclick="showRules('${id}')">View Rules Check</button>`:`<button class="primary" onclick="runRules('${c.governance.case_id}','${id}')">Run Rules Check</button>`}<div style="height:16px"></div><span class="pill ${c.governance.needs_attention?'warn':'good'}">${c.governance.needs_attention} actions need attention</span></div></div>
  ${hasRules?renderRulesAndActions(c.classifications,c.actions,false):''}`;
}

function renderRulesAndActions(profile, actions, detailed=true){
  return `<div class="grid" style="margin-top:18px"><div class="panel" style="grid-column:span 7"><div class="section-title"><div><p class="eyebrow">REGULATORY PROFILE</p><h2>Rules Check</h2></div></div><div class="profile">${profile.map(p=>`<div class="profile-row"><strong>${esc(labelDimension(p.dimension))}</strong><div><div class="result-main">${esc(labelOutcome(p.outcome))}</div>${p.explanation?`<div class="explain">${esc(p.explanation)}</div>`:''}${p.source?`<div class="source">${esc(p.source)}</div>`:''}</div><span class="pill ${badgeFor(p.outcome)}">${esc(p.confidence||'')}</span></div>`).join('')}</div></div><div class="panel" style="grid-column:span 5"><div class="section-title"><div><p class="eyebrow">WHAT YOU NEED TO DO</p><h2>Governance actions</h2></div></div><div class="actions-list">${actions.length?actions.map(a=>`<div class="action"><div class="priority ${a.priority}"></div><div><h4>${esc(a.title)}</h4><p>${esc(a.description)}</p>${a.source?`<div class="source" style="margin-top:6px">${esc(a.source)}</div>`:''}</div></div>`).join(''):'<p class="muted">No actions generated.</p>'}</div></div></div>`;
}

async function runRules(caseId,id){const r=await api(`/api/governance-cases/${caseId}/rules-check`,{method:'POST'}); app.innerHTML = `<div class="panel"><p class="eyebrow">RULES CHECK COMPLETE</p><h2>We translated the AI use into an explainable regulatory profile.</h2><p class="muted">This prototype intentionally uses screening conclusions such as “review required” where a full legal determination needs more facts or expert confirmation.</p><button class="secondary" onclick="openCard('${id}')">Back to AI card</button></div>`+renderRulesAndActions(r.regulatory_profile,r.actions);}
async function showRules(id){const c=await api(`/api/ai-uses/${id}/card`); /* show latest persisted summary plus action cards */ app.innerHTML=`<div class="panel"><button class="secondary" onclick="openCard('${id}')">← Back to AI card</button><p class="eyebrow" style="margin-top:22px">RULES CHECK</p><h2>${esc(c.name)}</h2><p class="muted">Current persisted regulatory profile. Re-running the rules check creates fresh evaluations in the backend.</p></div>`+renderRulesAndActions(c.classifications,c.actions,false);}

async function renderPeople(){
  navActive('people'); title.textContent='People';
  const [people,countries,groups]=await Promise.all([api('/api/people'),api('/api/reference/countries'),api('/api/groups')]);
  const countryMap=Object.fromEntries(countries.map(c=>[c.code,c.name]));
  app.innerHTML=`<div class="grid"><div class="panel" style="grid-column:span 12"><div class="section-title"><div><p class="eyebrow">ORGANISATION DIRECTORY</p><h2>People inventory</h2><p class="muted">People are maintained once and reused everywhere governance needs an owner, reviewer or approver.</p></div><button class="primary" onclick="openPersonModal()">+ Add person</button></div>
  <div class="directory">${people.map(p=>`<div class="person-row"><div><div class="person-name">${esc(p.display_name)}</div><div class="person-sub">${esc(p.email||'No email')}</div></div><div><strong>${esc(p.job_title||'No job title')}</strong><div class="person-sub">${esc(p.employment_type||'')}</div></div><div>${esc(countryMap[p.country_code]||p.country_code||'—')}</div><div><span class="pill ${p.status==='ACTIVE'?'good':''}">${esc(p.status)}</span></div><div class="tag-list">${(p.qualifications||[]).map(q=>`<span class="tag">${esc(q.type)}</span>`).join('')}</div></div>`).join('')}</div></div>
  <div class="panel" style="grid-column:span 12"><div class="section-title"><div><p class="eyebrow">ASSIGNABLE GROUPS</p><h2>Teams, functions & committees</h2></div></div>${groups.length?`<div class="ai-list">${groups.map(g=>`<div class="ai-card"><h3>${esc(g.name)}</h3><div class="card-meta"><span class="pill">${esc(g.group_type)}</span></div><p class="muted">${esc(g.description||'')}</p></div>`).join('')}</div>`:'<p class="muted">No groups yet.</p>'}</div></div>`;
}

async function openPersonModal(){
  const [countries,businessUnits,people]=await Promise.all([api('/api/reference/countries'),api('/api/business-units'),api('/api/people')]);
  modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">PEOPLE INVENTORY</p><h2>Add person</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body">
  <div class="choice-grid"><div class="field"><label>First name</label><input id="p-first"></div><div class="field"><label>Last name</label><input id="p-last"></div></div>
  <div class="field"><label>Email</label><input id="p-email" type="email"></div>
  <div class="choice-grid"><div class="field"><label>Job title</label><input id="p-title"></div><div class="field"><label>Employee ID</label><input id="p-employee"></div></div>
  <div class="choice-grid"><div class="field"><label>Business unit</label><select id="p-bu">${businessUnits.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Country</label><select id="p-country"><option value="">Select country</option>${countries.map(c=>`<option value="${c.code}">${esc(c.name)} (${c.code})</option>`).join('')}</select></div></div>
  <div class="choice-grid"><div class="field"><label>Manager</label><select id="p-manager"><option value="">No manager / unknown</option>${people.map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}</select></div><div class="field"><label>Authority level</label><select id="p-authority"><option value="">Not specified</option><option>INDIVIDUAL_CONTRIBUTOR</option><option>MANAGER</option><option>EXECUTIVE</option><option>GOVERNANCE_APPROVER</option></select></div></div>
  </div><div class="modal-footer"><button class="secondary" onclick="closeWizard()">Cancel</button><button class="primary" id="save-person">Add person</button></div></div></div>`;
  document.getElementById('save-person').onclick=async()=>{try{await api('/api/people',{method:'POST',body:JSON.stringify({first_name:document.getElementById('p-first').value.trim(),last_name:document.getElementById('p-last').value.trim(),email:document.getElementById('p-email').value.trim()||null,employee_id:document.getElementById('p-employee').value.trim()||null,job_title:document.getElementById('p-title').value.trim()||null,employment_type:'EMPLOYEE',business_unit_id:document.getElementById('p-bu').value||null,manager_person_id:document.getElementById('p-manager').value||null,country_code:document.getElementById('p-country').value||null,authority_level:document.getElementById('p-authority').value||null})});closeWizard();await renderPeople()}catch(e){alert(e.message)}};
}

async function openWizard(){
 const [people,countries]=await Promise.all([api('/api/people'),api('/api/reference/countries')]);
 if(!people.length){alert('Add at least one person to the People inventory before creating an AI use.'); await renderPeople(); return;}
 const data={step:0};
 const defaultOwner=people[0];
 const euPreferred=['FR','DE'];
 const steps=[
  {title:'What are you using AI for?',html:()=>`<div class="field"><label>Name this AI use</label><input id="f-name" value="Candidate screening" /></div><div class="field"><label>What are you trying to achieve?</label><textarea id="f-purpose">Help recruiters identify candidates whose experience matches job requirements.</textarea><small>We use this to understand the intended business purpose — you do not need legal terminology.</small></div><div class="field"><label>Business process</label><select id="f-process"><option>Recruitment</option><option>Customer service</option><option>Finance</option><option>Operations</option><option>Other</option></select></div><div class="field"><label>Business owner</label><select id="f-owner">${people.map(p=>`<option value="${p.id}" ${p.id===defaultOwner.id?'selected':''}>${esc(p.display_name)}${p.job_title?' — '+esc(p.job_title):''}</option>`).join('')}</select><small>Owners come from the People inventory so governance responsibilities stay consistent.</small></div>`,save:()=>Object.assign(data,{name:v('f-name'),business_purpose:v('f-purpose'),business_process:v('f-process'),owner_person_id:v('f-owner')})},
  {title:'What AI solution is involved?',html:()=>`<div class="field"><label>System or product name</label><input id="f-system" value="TalentAI" /></div><div class="field"><label>What is the system intended to do?</label><textarea id="f-syspurpose">Rank job applicants for recruiter review.</textarea></div><div class="field"><label>How is it supplied?</label><select id="f-supply"><option value="third_party">A product supplied by another company</option><option value="internal">Built internally</option><option value="hybrid">Combination of internal and external</option><option value="unknown">I don't know</option></select></div><div class="field"><label>Supplier</label><input id="f-supplier" value="TalentAI Vendor" /></div>`,save:()=>Object.assign(data,{system_name:v('f-system'),system_purpose:v('f-syspurpose'),supply_model:v('f-supply'),supplier_name:v('f-supplier')||null})},
  {title:'How does the AI influence decisions?',html:()=>`<div class="field"><label>What does the AI do?</label><select id="f-function"><option value="ranking">Rank people or options</option><option value="scoring">Score something</option><option value="selection">Select/filter</option><option value="evaluation">Evaluate</option><option value="generation">Generate content</option><option value="chatbot">Interact with people</option></select><small>This helps the Rules Check classify the use — you do not need to know the legal category.</small></div><div class="field"><label>Which decision area is involved?</label><select id="f-domain"><option value="employment">Employment / recruitment</option><option value="education">Education</option><option value="credit">Credit / financial services</option><option value="healthcare">Healthcare</option><option value="other">Other</option></select></div><div class="field"><label>Who makes the final decision?</label><select id="f-human"><option value="true">A person makes the final decision</option><option value="false">The AI can make/execute the final decision</option></select></div>`,save:()=>Object.assign(data,{function:v('f-function'),decision_domain:v('f-domain'),human_final_decision:v('f-human')==='true'})},
  {title:'Who could be affected, and where?',html:()=>`<div class="field"><label>Who could be affected?</label><select id="f-pop"><option value="job_applicants">Job applicants</option><option value="employees">Employees</option><option value="customers">Customers</option><option value="patients">Patients</option><option value="students">Students</option><option value="general_public">General public</option></select></div><div class="field"><label>Countries</label><select id="f-countries" class="country-select" multiple>${countries.map(c=>`<option value="${c.code}" ${euPreferred.includes(c.code)?'selected':''}>${esc(c.name)} (${c.code})${c.eu_member?' · EU':''}</option>`).join('')}</select><small>Select one or more countries from the ISO 3166-1 directory. Hold Ctrl/Cmd to select multiple countries.</small></div>`,save:()=>Object.assign(data,{affected_population:v('f-pop'),countries:[...document.getElementById('f-countries').selectedOptions].map(o=>o.value)})},
  {title:'Review your AI use',html:()=>`<div class="panel" style="box-shadow:none;padding:18px"><p class="eyebrow">AI USE SUMMARY</p><h2>${esc(data.name)}</h2><p>${esc(data.business_purpose)}</p><div class="kv"><span>Business owner</span><span>${esc((people.find(p=>p.id===data.owner_person_id)||{}).display_name||'')}</span></div><div class="kv"><span>System</span><span>${esc(data.system_name)}</span></div><div class="kv"><span>Supply</span><span>${esc(data.supply_model)}</span></div><div class="kv"><span>Function</span><span>${esc(data.function)}</span></div><div class="kv"><span>Decision area</span><span>${esc(data.decision_domain)}</span></div><div class="kv"><span>Affected people</span><span>${esc(data.affected_population)}</span></div><div class="kv"><span>Countries</span><span>${esc(data.countries.map(code=>(countries.find(c=>c.code===code)||{name:code}).name).join(', '))}</span></div></div><p class="muted">Behind the scenes this creates linked inventory records using controlled people and country references.</p>`,save:()=>{}},
 ];
 function v(id){return document.getElementById(id).value.trim()}
 function draw(){const s=steps[data.step];modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ADD AI USE · ${data.step+1} OF ${steps.length}</p><h2>${s.title}</h2></div><button class="secondary" onclick="closeWizard()">Close</button></div><div class="modal-body"><div class="steps">${steps.map((_,i)=>`<div class="step-dot ${i<data.step?'done':i===data.step?'active':''}"></div>`).join('')}</div>${s.html()}</div><div class="modal-footer"><button class="secondary" id="back" ${data.step===0?'disabled':''}>Back</button><button class="primary" id="next">${data.step===steps.length-1?'Create AI use':'Continue'}</button></div></div></div>`;document.getElementById('back').onclick=()=>{if(data.step){data.step--;draw()}};document.getElementById('next').onclick=async()=>{s.save();if(data.step===3&&!data.countries.length){alert('Select at least one country.');return;}if(data.step<steps.length-1){data.step++;draw()}else{try{const created=await api('/api/ai-uses',{method:'POST',body:JSON.stringify(data)});closeWizard();await openCard(created.ai_use_id)}catch(e){alert(e.message)}}};}
 draw();
}
function closeWizard(){modalRoot.innerHTML=''}
window.openWizard=openWizard;window.closeWizard=closeWizard;window.renderPortfolio=renderPortfolio;window.openCard=openCard;window.runRules=runRules;window.showRules=showRules;window.renderPeople=renderPeople;window.openPersonModal=openPersonModal;

document.getElementById('new-ai').onclick=openWizard;
document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>({home:renderHome,portfolio:renderPortfolio,actions:renderActions,people:renderPeople}[b.dataset.view]||renderHome)());
renderHome().catch(e=>{app.innerHTML=`<div class="panel"><h2>Backend not reachable</h2><p class="muted">Start the FastAPI backend on port 8000, then refresh.</p><pre>${esc(e.message)}</pre></div>`});
